import { AllFunctions } from "./func";

export const unsortedAllowedEventTypes = [
  "",
  "Arbetsplatsolycka",
  "Stöld",
  "Inbrott",
  "Trafikolycka",
  "Trafikbrott",
  "Misshandel",
  "Rån",
  "Brand",
  "Trafikolycka, personskada",
  "Rattfylleri",
  "Trafikolycka, singel",
  "Försvunnen person",
  "Olaga hot",
  "Mord/dråp",
  "Trafikkontroll",
  "Misshandel, grov",
  "Våldtäkt",
  "Övrigt",
  "Sammanfattning natt",
  "Olaga intrång",
  "Narkotikabrott",
  "Explosion",
  "Bedrägeri",
  "Stöld/inbrott",
  "Fjällräddning",
  "Vapenlagen",
  "Trafikolycka, vilt",
  "Kontroll person/fordon",
  "Knivlagen",
  "Motorfordon, stöld",
  "Fylleri/LOB",
  "Mord/dråp, försök",
  "Trafikolycka, smitning från",
  "Räddningsinsats",
  "Skadegörelse",
  "Häleri",
  "Larm Inbrott",
  "Rån, försök",
  "Hemfridsbrott",
  "Våld/hot mot tjänsteman",
  "Olovlig körning",
  "Trafikhinder",
  "Sammanfattning kväll och natt",
  "Polisinsats/kommendering",
  "Larm Överfall",
  "Farligt föremål, misstänkt",
  "Rån övrigt",
  "Skottlossning",
] as const;

export const allowedEventTypes = [...unsortedAllowedEventTypes].sort();
